#!/bin/bash

if [ -x /etc/init.d/shimsvc ]
then
    /etc/init.d/shimsvc stop
fi

if [ -z "$SCIDB_INSTALL_PATH" ]
then
    export SCIDB_INSTALL_PATH=/opt/scidb/18.1
fi


scidbuser=$(                                    \
    ps axfo user:64,cmd                         \
    |  grep scidb                               \
    |  grep dbname                              \
    |  head -n 1                                \
    |  cut -d ' ' -f 1)
basepath=$(                                     \
    cat $SCIDB_INSTALL_PATH/etc/config.ini      \
    |  grep base-path                           \
    |  cut -d = -f 2)

sed -i "s/LOGNAME/$scidbuser/"                        /var/lib/shim/conf
sed -i "s:\[INSTANCE_0_DATA_DIR\]:$basepath/0/0/tmp:" /var/lib/shim/conf


if [ ! -f /var/lib/shim/ssl_cert.pem ]
then
    openssl req                                                         \
        -new                                                            \
        -newkey rsa:4096                                                \
        -days 3650                                                      \
        -nodes                                                          \
        -x509                                                           \
        -subj "/C=US/ST=MA/L=Waltham/O=Paradigm4/CN=$(hostname)"        \
        -keyout /var/lib/shim/ssl_cert.pem                              \
    2> /dev/null                                                        \
    >> /var/lib/shim/ssl_cert.pem
fi


if [ -x /etc/init.d/shimsvc ]
then
    /etc/init.d/shimsvc start
fi
